In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [4]:
#Load Data Set
df = pd.read_csv(r"C:\Users\mggon\Documents\Repositories\HW\homework\Data_Plant_New.csv")

In [5]:
df.head(10)

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
0,39527.25208,27.471821,27.566410,8.869142,5.396484,1698.780029,7.370453,78.717918,13.69824,36.843750,...,3.037109,55.956829,71.275284,30.619141,30.603519,380038.1875,45.984451,3.265625,2.267195,1.720545
1,39527.25417,27.477289,27.539061,8.734374,5.404296,1703.457031,7.374215,78.399452,13.74219,36.843750,...,3.066406,55.962200,71.275284,30.607910,30.572269,389348.0000,45.977341,3.243652,NaN,1.700500
2,39527.25625,27.482759,NaN,8.734374,5.427734,1699.296997,7.377976,78.485107,13.86719,36.843750,...,3.059082,55.967579,71.275284,30.592581,30.598829,385134.5938,45.970242,3.265625,2.263300,1.700500
3,39527.25833,27.488220,27.476561,8.756347,5.427734,1686.083984,7.381738,78.517532,13.74219,36.843750,...,3.037109,55.972950,71.275284,30.648439,30.616800,359803.0000,45.963131,3.265625,2.263300,1.700500
4,39527.26042,27.493690,27.468750,8.756347,5.427734,1691.494019,7.385500,78.575523,13.68359,36.843750,...,3.037109,55.978321,71.275284,30.632811,30.576960,376974.5938,45.956032,3.265625,2.263300,1.700500
5,39527.26250,27.499161,27.737310,8.822266,5.427734,1684.032959,7.389262,78.636162,13.62109,36.843750,...,3.037109,55.983688,71.275284,30.632811,30.572269,373914.4063,45.948929,3.265625,2.263300,1.700500
6,39527.26458,27.503080,28.640631,9.648439,5.488281,1704.883057,7.393024,78.628601,13.57421,36.937500,...,3.128906,55.989059,71.275284,30.690620,30.648439,397545.1875,45.941818,3.296875,2.263910,1.703245
7,39527.26667,27.496700,28.394529,9.537109,5.457031,1686.991943,7.396786,78.825798,14.23437,37.119141,...,3.059082,55.994431,71.275284,30.664061,30.616800,384739.3125,45.934719,3.320313,2.275500,1.755400
8,39527.26875,27.490320,28.534180,9.191404,5.548828,1692.764038,7.400548,78.663643,14.66406,37.212891,...,3.158203,55.999802,71.275284,30.619141,30.592581,377052.1875,46.068630,3.289063,2.275500,1.755400
9,39527.27083,27.483950,28.394529,9.466796,5.526855,1692.772949,7.404310,78.446083,14.84766,37.306641,...,3.150879,56.005169,71.275284,30.603519,30.590231,390613.3125,46.229080,3.328125,2.275500,1.755400

In [6]:
df.describe()

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
count,7199.000000,7198.000000,7198.000000,7199.000000,7199.000000,7199.000000,7199.000000,7199.000000,7199.000000,7199.000000,...,7199.000000,7198.000000,7199.000000,7199.000000,7198.000000,7199.000000,7199.000000,7199.000000,7198.000000,7197.000000
mean,39534.750000,27.127295,27.953209,9.593198,6.395699,1701.915367,11.555007,76.332696,18.356032,37.815861,...,3.620778,52.985809,70.771369,30.648593,30.609367,386035.274340,45.167884,3.841032,2.114043,0.692348
std,4.329826,0.674680,0.698533,0.630545,0.952640,99.738546,2.901431,3.595688,3.648891,1.768092,...,0.623456,1.915064,1.725054,0.192165,0.194832,18811.255389,14.682053,0.619553,0.637675,17.474702
min,39527.252080,24.231501,24.593750,7.673828,4.951172,687.060486,6.780738,18.643391,8.441406,35.882809,...,2.455078,47.744381,0.000000,29.974609,30.035160,236985.406300,12.223560,0.000000,-8.956800,-320.799988
25%,39531.001040,26.652867,27.507811,9.191404,5.640625,1659.447998,9.108021,74.057091,15.921870,37.166019,...,3.158203,51.530783,71.275284,30.534136,30.497549,375581.046900,38.216480,3.388672,1.930599,1.390500
50%,39534.750000,27.109890,27.906250,9.570802,6.177734,1697.920044,11.137910,76.542381,19.292971,37.535160,...,3.511719,53.136414,71.275284,30.603519,30.573830,386836.500000,47.806690,3.737500,2.160500,1.642300
75%,39538.498960,27.518567,28.394529,9.923826,6.958984,1751.557495,13.789635,78.800842,21.316410,37.904301,...,4.030078,54.495871,71.275284,30.724609,30.679689,397080.296900,55.019815,4.246094,2.328500,1.789600
max,39542.247920,47.017712,42.443359,17.277340,19.515141,2235.039063,26.766680,84.796471,29.253910,64.715332,...,15.594240,57.336620,71.275284,31.686710,31.644920,643457.375000,90.493187,14.015130,4.172300,135.899994

In [7]:
df.shape

(7199, 27)

In [8]:
df.columns = df.columns.str.upper()

2.	Check for missing values in the dataset. Use the attribute mean to fill in the missing value.

In [9]:
df.isnull().sum().sum()

np.int64(11)

In [10]:
df_mean = df.fillna(df.mean())

In [11]:
df_drop_dup = df.drop_duplicates()

3.	Split the preprocessed data for training, validation and testing. The data should be split will be 70% training, 15% validation and the testing will be 15%. Show the length of each split.

In [12]:
x_train, x_test = train_test_split(df, test_size = 0.7, random_state=42)
x_train2, x_val = train_test_split(x_train, test_size = 0.16, random_state=42)

In [13]:
print(len(x_train2))
print(len(x_test))
print(len(x_val))

1813
5040
346

4.	Using any transformation methods, normalize/standardize all numerical features.

In [14]:
x_train2.head()

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
5511,39538.73333,27.374201,28.027340,10.064450,6.515625,1709.961060,12.526370,76.970734,20.618759,37.400391,...,3.603516,55.274929,71.275284,30.500000,30.519039,395983.4063,52.940739,3.833984,2.0817,2.24840
3430,39534.39792,26.901360,27.539061,9.373048,5.472656,1765.428955,9.276216,77.721786,15.550780,36.984379,...,3.097656,52.874359,71.275284,30.556641,30.511721,401824.3125,84.589310,3.359375,1.9558,1.92880
6870,39541.56458,27.722469,27.843750,9.518359,6.759766,1762.900024,13.478130,73.442673,20.578131,38.455078,...,3.878906,55.032879,71.275284,30.724609,30.664061,361405.4063,53.120972,4.185547,1.7892,1.78320
5772,39539.27708,26.046940,26.894529,8.916018,5.978516,1704.150024,10.960760,79.528038,18.433590,37.031250,...,3.451172,50.628441,71.275284,30.607429,30.552731,414154.4063,45.611340,3.619141,2.6769,1.70560
3642,39534.83958,27.814671,28.546881,9.835939,7.341797,1646.240967,14.110910,72.263557,22.234381,37.998051,...,4.277344,53.000729,71.275284,30.744921,30.668751,371514.1875,41.081249,4.431641,2.1907,0.99076

In [15]:
x_val.head()

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
3073,39533.65417,27.410160,27.691410,9.191404,8.526172,1826.758057,16.866159,71.906403,22.816410,37.810551,...,4.660156,52.593262,71.275284,30.787109,30.679689,379860.4063,23.543270,4.890625,2.6252,1.2293
454,39528.19792,27.160400,28.148439,9.242675,5.427734,1693.691040,7.486065,83.224167,11.628910,36.802731,...,3.037109,53.978760,71.275284,30.738770,30.723930,384254.0000,57.550621,3.237793,2.1406,1.8321
1500,39530.37708,26.538280,27.722660,9.285156,5.365234,1691.766968,7.677331,79.850639,11.015630,36.708981,...,2.960938,55.239300,71.275284,30.572269,30.587891,357864.8125,54.264320,3.158203,2.1933,1.5845
66,39527.38958,27.120440,27.812500,9.075684,5.548828,1746.055054,8.559603,78.427979,12.855470,37.031250,...,3.335938,56.087891,71.052773,30.632811,30.603519,387790.0000,28.445101,3.527344,2.3480,1.6456
5490,39538.68958,27.309601,27.812500,10.339850,6.806640,1707.177979,12.956400,77.008148,21.200781,37.582031,...,3.849609,55.179352,71.275284,30.541019,30.480471,395934.0000,51.171162,4.109375,2.1965,2.3921

In [16]:
x_test

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
4899,39537.45833,26.856621,28.335939,10.246090,6.969922,1751.661011,13.766950,74.861328,21.468750,37.689850,...,3.941406,50.260651,71.275284,30.556641,30.496090,392382.0938,50.605370,4.154297,2.0101,1.4565
2531,39532.52500,26.997290,27.937500,10.568360,7.126954,1772.802002,14.088550,73.939598,21.804689,37.951172,...,3.970703,55.193821,71.275284,30.572269,30.506250,376612.4063,14.337550,4.201172,2.0313,1.5887
6652,39541.11042,26.567160,27.906250,9.875488,5.595703,1467.578003,9.141704,73.797562,15.062500,37.628910,...,3.097656,50.648178,71.275284,30.771481,30.755859,343870.0938,48.721340,3.359864,1.4176,1.7067
1287,39529.93333,26.568489,27.476561,9.560548,5.718750,1679.735962,9.518938,79.000473,17.054689,37.119141,...,3.128906,50.474110,71.275284,30.511721,30.503910,385162.1875,39.589920,3.328125,2.1309,2.1151
2540,39532.54375,26.976641,27.903130,10.292970,6.974609,1778.046997,14.338120,74.038147,21.558590,37.857422,...,3.849609,55.320209,71.275284,30.572269,30.511721,380574.9063,14.009740,4.048828,2.0625,1.4125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4470,39536.56458,27.717760,27.750000,9.695311,5.427734,1760.791016,8.824684,77.580673,16.625000,37.259769,...,2.945313,50.191589,71.275284,30.520611,30.480471,395516.5000,63.501930,3.173828,1.9307,1.1635
891,39529.10833,27.740589,28.609381,9.835939,5.611328,1715.937988,7.683429,83.273117,11.136720,37.031250,...,3.296875,52.659191,71.275284,30.712400,30.710939,366856.8125,58.010841,3.527344,2.3562,1.5905
2793,39533.07083,26.530161,27.445311,9.238280,5.718750,1678.906006,10.235150,77.560959,17.118160,37.301960,...,3.144531,53.370499,71.275284,30.532909,30.464840,380858.8125,55.398331,3.404297,1.8216,1.8389
6044,39539.84375,26.117920,26.953131,8.734374,5.947266,1547.265991,11.664100,74.766083,18.738279,36.708981,...,3.128906,53.587650,71.183281,30.603519,30.603519,371351.0000,37.899349,3.451172,3.9392,2.4276
4403,39536.42500,26.271170,27.167000,8.869142,5.656250,1746.376953,9.838668,80.617554,17.057810,37.166019,...,3.097656,49.993969,71.275284,30.541019,30.496090,405741.9063,57.758072,3.314063,2.5063,1.2753

Scaling

In [17]:
scaler = StandardScaler().fit(x_train2)

In [18]:
df_scaled = scaler.transform(x_train2)

In [19]:
df_scaled

array([[ 0.91518458,  0.40555733,  0.1133387 , ..., -0.04500672,
        -0.05923724,  0.09562708],
       [-0.09123003, -0.37724938, -0.63762859, ..., -0.87462536,
        -0.2670856 ,  0.07703292],
       [ 1.57242607,  0.98212911, -0.16902024, ...,  0.56952706,
        -0.54212572,  0.06856199],
       ...,
       [-0.13233939, -0.45898298, -0.07289606, ..., -1.14433746,
         0.3242665 ,  0.07190731],
       [ 1.43798086, -1.24422114, -1.91126817, ...,  1.23868432,
         0.75267508,  0.06329093],
       [-0.85341891, -1.01787488, -0.87793905, ..., -0.47517812,
        -0.49457978,  0.06194116]])

Transformation

In [20]:
def log_transform(x):
    return np.log(x + 1)

df_log = log_transform(df_scaled)

C:\Users\mggon\AppData\Local\Temp\ipykernel_24208\859287776.py:2: RuntimeWarning: invalid value encountered in log
  return np.log(x + 1)

In [21]:
df_log

array([[ 0.649814  ,  0.3404339 ,  0.10736333, ..., -0.04605098,
        -0.06106429,  0.09132688],
       [-0.09566327, -0.47360914, -1.01508559, ..., -2.07644894,
        -0.31072637,  0.07420997],
       [ 0.94484945,  0.68417158, -0.18514984, ...,  0.45077434,
        -0.78116062,  0.06631381],
       ...,
       [-0.14195465, -0.61430455, -0.07568959, ...,         nan,
         0.28085872,  0.0694396 ],
       [ 0.89117018,         nan,         nan, ...,  0.80588834,
         0.56114324,  0.06136875],
       [-1.9201765 ,         nan, -2.10323477, ..., -0.64469634,
        -0.68236507,  0.06009852]])